itemDict:
    'uncal_sntemp_input_output.zip': '623e5587d34e915b67d83806' 
    'distance_matrix_drb.csv': '5f6a289982ce38aaa2449135'
    'reach_attributes_drb.csv': '5f6a289982ce38aaa2449135'
    'aggregated_temperature_observations_drb.zip': '623e550ad34e915b67d8366e'
    'flow_observations_drb.zip': '623e550ad34e915b67d8366e'  

subsetDict: 
    Christiana: "ChristianaReaches.csv"
    Trenton: "TrentonReaches.csv"

#this contains the min and max values for the noted variables. values above / below these are set to na
qaDict:
    seg_tave_water:
        min: -50
        max: 50
        na_action: False
    discharge_cms:
        min: 0
        max: False
        na_action: False
    seg_tave_gw:
        min: 0
        max: 50
        na_action: 'mean' #method for interpolating for missing data, any pandas aggregation function or False (no interpolation)
        na_by: [] #list of grouping columns for interpolation (seg_id_nat, date, etc)
    seg_tave_upstream:
        min: -10
        max: 50
        na_action: 'mean' #method for interpolating for missing data, any pandas aggregation function or False (no interpolation)
        na_by: ['date'] #list of grouping columns for interpolation (seg_id_nat, date, etc)
        
#this is a dictionary of variables to aggregate
aggDict:
    seg_width:
        agg_level: 'seg_id_nat'
        agg_function: 'mean' #any pandas aggregation function or False (no aggregation)

outDir: "../../../../caldera/projects/usgs/water/impd/pump/drb-gw-hw-temp/data_DRB" 

#suffix added to the end of the output files
suffix: "no3558_202208" 
#suffix: ""

tarFiles: False 

segsToExclude: [3558]
#segsToExclude: []
